version: '3.9'

services:

  db:
    image: postgres
    container_name: db-organizzi
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: q1w2e3r4
    ports:
      - "8080:8080"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
      
  api: 
    build:
    context: ./api
    dockerfile: Dockerfile
